### ISSUE TITLE
Time to start making Bullseye hooks?

### ISSUE THREAD

**Issue by triantares** [Elive/elive-upgrader#1]
Considering the availability and use of Bullseye for Elive ...... time to accommodate it in elive-upgrade?

**Comment by Thanatermesis** [comment]
nope, bullseye is not yet officially supported (or more like "published"), we will switch entirely to it after the first build based on bullseye, which requires:
* a lot of work on the live building system
* the elive website needs to move to the new server (that's on the way already)
